### PR TITLE
Adjust author and resolve conflict

### PR DESCRIPTION
**Pull request by mootrichard**
I had amended the author on the commits that I had wrongly attributed.

I also cleaned up the conflict with the `RNInAppPaymentsQuickstart.xcodeproj/project.pbxproj`

### CODE REVIEW

**Comment by mootrichard** [comment]
Errr. Or maybe I _didn't_ resolve those. 🤦‍♂

**Comment by mootrichard** [comment]
Okay. _NOW_ I have amended those darned merge conflicts.

**Comment by joshed-io** [comment]
Thanks @mootrichard!

**Comment by mootrichard** [comment]
I think you should revert this PR. I think that I totally screwed up when created it.

**Comment by joshed-io** [comment]
@mootrichard I went ahead and hard reset the `cardonfile` branch to the commit just before these.

**Pull request merged**
